In [1]:
import pandas as pd

import tensorflow as tf
import utils
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dfs = []

dfs.append(pd.read_csv('game_51-100_min7.csv'))
dfs.append(pd.read_csv('game_101-200_min7.csv'))
dfs.append(pd.read_csv('game_201-300_min7.csv'))
dfs.append(pd.read_csv('game_351-400_min7.csv'))
dfs.append(pd.read_csv('game_401-450_min7.csv'))
dfs.append(pd.read_csv('game_451-500_min7.csv'))
dfs.append(pd.read_csv('game_501-600_min7.csv'))
dfs.append(pd.read_csv('game_701-800_min7.csv'))
dfs.append(pd.read_csv('game_801-900_min7.csv'))
dfs.append(pd.read_csv('game_901-1000_min7.csv'))
dfs.append(pd.read_csv('game_1001-1100_min7.csv'))
dfs.append(pd.read_csv('game_1101-1500_min7.csv'))

df = pd.concat(dfs)
df

       Unnamed: 0    id             name            user  rating
0               0    51  Ricochet Robots         Haffner    10.0
1               1    51  Ricochet Robots          schris    10.0
2               2    51  Ricochet Robots      Sushionrye    10.0
3               3    51  Ricochet Robots     Bart_Massey    10.0
4               4    51  Ricochet Robots    MisterCranky    10.0
...           ...   ...              ...             ...     ...
26400       26400  1499  World in Flames       Lord_Baer     1.0
26401       26401  1499  World in Flames  zombiemaster22     1.0
26402       26402  1499  World in Flames          Gardey     1.0
26403       26403  1499  World in Flames          keithm     1.0
26404       26404  1499  World in Flames    meepleraptor     1.0

[812504 rows x 5 columns]

In [3]:
df = df[['id', 'name', 'user', 'rating']]
df

         id             name            user  rating
0        51  Ricochet Robots         Haffner    10.0
1        51  Ricochet Robots          schris    10.0
2        51  Ricochet Robots      Sushionrye    10.0
3        51  Ricochet Robots     Bart_Massey    10.0
4        51  Ricochet Robots    MisterCranky    10.0
...     ...              ...             ...     ...
26400  1499  World in Flames       Lord_Baer     1.0
26401  1499  World in Flames  zombiemaster22     1.0
26402  1499  World in Flames          Gardey     1.0
26403  1499  World in Flames          keithm     1.0
26404  1499  World in Flames    meepleraptor     1.0

[812504 rows x 4 columns]

In [4]:
df['rating'] = df['rating'].astype('float32')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 812504 entries, 0 to 26404
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      812504 non-null  int64
 1   name    812504 non-null  object
 2   user    812499 non-null  object
 3   rating  812504 non-null  float32
dtypes: float32(1), int64(1), object(2)
memory usage: 27.9+ MB

C:\Users\fuze0\AppData\Local\Temp\ipykernel_21892\776453335.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].astype('float32')

In [5]:
df.drop_duplicates(subset=['user', 'name', 'rating'], inplace=True)

C:\Users\fuze0\AppData\Local\Temp\ipykernel_21892\1093089643.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset=['user', 'name', 'rating'], inplace=True)

In [6]:
df.duplicated(subset=['user', 'name', 'rating']).value_counts()
df.duplicated(subset=['user', 'name']).value_counts()

False    734787
True       1618
Name: count, dtype: int64

In [7]:
df.drop_duplicates(subset=['user', 'name'], inplace=True, keep='last')
df.duplicated(subset=['user', 'name']).value_counts()

C:\Users\fuze0\AppData\Local\Temp\ipykernel_21892\3513245203.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset=['user', 'name'], inplace=True, keep='last')

False    734787
Name: count, dtype: int64

In [8]:
df.dropna(subset=['id', 'name', 'user'], how='any', inplace=True)
df

C:\Users\fuze0\AppData\Local\Temp\ipykernel_21892\1357015060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=['id', 'name', 'user'], how='any', inplace=True)

         id             name            user  rating
0        51  Ricochet Robots         Haffner    10.0
1        51  Ricochet Robots          schris    10.0
2        51  Ricochet Robots      Sushionrye    10.0
3        51  Ricochet Robots     Bart_Massey    10.0
4        51  Ricochet Robots    MisterCranky    10.0
...     ...              ...             ...     ...
26400  1499  World in Flames       Lord_Baer     1.0
26401  1499  World in Flames  zombiemaster22     1.0
26402  1499  World in Flames          Gardey     1.0
26403  1499  World in Flames          keithm     1.0
26404  1499  World in Flames    meepleraptor     1.0

[734783 rows x 4 columns]

In [9]:
pivot_df = df.pivot(index='user', columns=['name'], values=['rating'])
# pivot_df.dropna(subset='user', inplace=True, axis=1)
pivot_df.columns = pivot_df.columns.droplevel()
pivot_df

name,1826: Railroading in France and Belgium from 1826,1830: Railways & Robber Barons,1835,1841: Railways in Northern Italy,1856: Railroading in Upper Canada from 1856,1870: Railroading Across the Trans Mississippi from 1870,2038: Tycoons of the Asteroid Belt,A House Divided: War Between the States 1861-65,APBA Pro Baseball,Ace of Aces: Handy Rotary Series,...,Up Front,Victory in the Pacific,Vinci,VolgaFront: East of EastFront 1942-43,War of Resistance,Warangel,Web of Power,Wooden Ships & Iron Men,World in Flames,ZÈRTZ
user,,,,,,,,,,,,,,,,,,,,,
beastvol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mycroft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
woh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
- V -,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-=Yod@=-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zzzoren,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zzzuzu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zzzvone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zzzxxxyyy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zzzzzane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# 99873, 109917

# Drop users that have only rated 1 game
pivot_df.dropna(thresh=3, inplace=True)
pivot_df

# 46640, 55149
# 33627

name,1826: Railroading in France and Belgium from 1826,1830: Railways & Robber Barons,1835,1841: Railways in Northern Italy,1856: Railroading in Upper Canada from 1856,1870: Railroading Across the Trans Mississippi from 1870,2038: Tycoons of the Asteroid Belt,A House Divided: War Between the States 1861-65,APBA Pro Baseball,Ace of Aces: Handy Rotary Series,...,Up Front,Victory in the Pacific,Vinci,VolgaFront: East of EastFront 1942-43,War of Resistance,Warangel,Web of Power,Wooden Ships & Iron Men,World in Flames,ZÈRTZ
user,,,,,,,,,,,,,,,,,,,,,
-=Yod@=-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Johnny-,NaN,4.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Loren-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Morphling-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-mIDE-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zzzhsm,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zzzoren,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zzzuzu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zzzvone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zzzzzane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
pivot_df.fillna(value=0, inplace=True)

In [43]:
len(pivot_df.columns)

53

In [12]:
normalized_df = pivot_df / 10
normalized_df

name,1826: Railroading in France and Belgium from 1826,1830: Railways & Robber Barons,1835,1841: Railways in Northern Italy,1856: Railroading in Upper Canada from 1856,1870: Railroading Across the Trans Mississippi from 1870,2038: Tycoons of the Asteroid Belt,A House Divided: War Between the States 1861-65,APBA Pro Baseball,Ace of Aces: Handy Rotary Series,...,Up Front,Victory in the Pacific,Vinci,VolgaFront: East of EastFront 1942-43,War of Resistance,Warangel,Web of Power,Wooden Ships & Iron Men,World in Flames,ZÈRTZ
user,,,,,,,,,,,,,,,,,,,,,
-=Yod@=-,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-Johnny-,0.0,0.4,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-Loren-,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-Morphling-,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-mIDE-,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zzzhsm,0.0,0.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zzzoren,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zzzuzu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zzzvone,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zzzzzane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
X = normalized_df.values
X

array([[0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0.4, 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ]], dtype=float32)

In [14]:
hiddenUnits = 20
visibleUnits = len(normalized_df.columns)

# Set the bias of visible layer to 0
visible_layer_bias = tf.Variable(tf.zeros([visibleUnits]), tf.float32)

# Set the bias of hidden layer to 0
hidden_layer_bias = tf.Variable(tf.zeros([hiddenUnits]), tf.float32)

# Set the weights to 0
W = tf.Variable(tf.zeros([visibleUnits, hiddenUnits]), tf.float32)

In [15]:
# Initialize v0 with first row

# v0 = tf.Variable(normalized_df.iloc[0].values)
v0 = tf.Variable(X[0])
tf.matmul([v0], W)

<tf.Tensor: shape=(1, 20), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)>

In [16]:
# Phase 1: Input processing

# Define a function to return only the generated hidden states
def hidden_layer(v0_state, W, hb):
    # Probabilities of the hidden units
    h0_prob = tf.nn.sigmoid(tf.linalg.matmul([v0_state], W) + hb)
    # sample_h_given_X
    h0_state = tf.nn.relu(tf.sign(h0_prob - tf.random.uniform(tf.shape(h0_prob))))
    return h0_state

# Print output of zeros input
# h0 = hidden_layer(v0, W, hidden_layer_bias)
# print(f"First 15 hidden states: ", h0[0][0:15])

# Back Propagation
# Define a function to return the reconstructed output
def reconstructed_ouptput(h0_state, W, vb):
    v1_prob = tf.nn.sigmoid(tf.linalg.matmul(h0_state, tf.transpose(W)) + vb)
    # sample_v_given_h
    v1_state = tf.nn.relu(tf.sign(v1_prob - tf.random.uniform(tf.shape(v1_prob))))[0]
    return v1_state

# v1 = reconstructed_ouptput(h0, W, visible_layer_bias)

# Mean Absolute Error
def error(v0_state, v1_state):
    return tf.reduce_mean(tf.square(v0_state - v1_state))

In [17]:
# Set the training variables
epochs = 20
batchsize = 10000
errors = []
weights = []
K = 2
alpha = 0.04

# Create list of batches
train_ds = tf.data.Dataset.from_tensor_slices((np.float32(X))).batch(batchsize)

v0_state = tf.Variable(X[0])

# Train the model

for epoch in range(epochs):
    batch_number = 0
    for batch_x in train_ds:
        for i_sample in range(len(batch_x)):
            v0_state = batch_x[i_sample]
            for k in range(K):
                h0_state = hidden_layer(v0_state, W, hidden_layer_bias)
                v1_state = reconstructed_ouptput(h0_state, W, visible_layer_bias)
                h1_state = hidden_layer(v1_state, W, hidden_layer_bias)

                delta_W = tf.linalg.matmul(tf.transpose([v0_state]), h0_state) \
                            - tf.linalg.matmul(tf.transpose([v1_state]), h1_state)
                
                # Update weights
                W = W + alpha * delta_W

                # Update biases
                visible_layer_bias = visible_layer_bias + alpha * tf.reduce_mean(v0_state - v1_state, 0)
                hidden_layer_bias = hidden_layer_bias + alpha * tf.reduce_mean(h0_state - h1_state, 0)

                v0_state = v1_state

            if i_sample == len(batch_x) - 1:
                err = error(batch_x[i_sample], v1_state)
                errors.append(err)
                weights.append(W)
                print('Epoch: %d' % (epoch + 1),
                      'batch #: %i ' % (batch_number + 1), 'of %i' % (len(X) / batchsize + 1),
                      'sample #: %i ' % (i_sample + 1),
                      'reconstruction error: %f' % err)
                
        batch_number += 1

plt.plot(errors)
plt.ylabel('Error')
plt.xlabel('Batch')
plt.show()

Epoch: 1 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.011918
Epoch: 1 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.137608
Epoch: 1 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.050000
Epoch: 1 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.041336
Epoch: 1 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.043470
Epoch: 1 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.064007
Epoch: 1 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.138578
Epoch: 1 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.074138
Epoch: 2 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.033470
Epoch: 2 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.153125
Epoch: 2 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.100000
Epoch: 2 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.013750
Epoch: 2 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.052091
Epoch: 2 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.128404
Epoch: 2 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.128233
Epoch: 2 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.075862
Epoch: 3 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.025711
Epoch: 3 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.145366
Epoch: 3 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.098276
Epoch: 3 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.067198
Epoch: 3 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.060711
Epoch: 3 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.067369
Epoch: 3 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.063578
Epoch: 3 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.082759
Epoch: 4 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.047263
Epoch: 4 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.148815
Epoch: 4 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.101724
Epoch: 4 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.028405
Epoch: 4 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.034849
Epoch: 4 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.077714
Epoch: 4 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.060991
Epoch: 4 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.050000
Epoch: 5 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.034332
Epoch: 5 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.125539
Epoch: 5 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.105172
Epoch: 5 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.030991
Epoch: 5 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.043470
Epoch: 5 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.080818
Epoch: 5 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.067888
Epoch: 5 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.106897
Epoch: 6 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.030022
Epoch: 6 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.123815
Epoch: 6 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.056897
Epoch: 6 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.028405
Epoch: 6 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.064159
Epoch: 6 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.069611
Epoch: 6 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.043750
Epoch: 6 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.081034
Epoch: 7 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.046401
Epoch: 7 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.158297
Epoch: 7 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.118966
Epoch: 7 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.019784
Epoch: 7 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.103815
Epoch: 7 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.060990
Epoch: 7 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.088578
Epoch: 7 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.051724
Epoch: 8 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.021401
Epoch: 8 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.085884
Epoch: 8 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.070690
Epoch: 8 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.032716
Epoch: 8 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.057263
Epoch: 8 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.072800
Epoch: 8 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.073060
Epoch: 8 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.056897
Epoch: 9 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.080884
Epoch: 9 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.133297
Epoch: 9 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.075862
Epoch: 9 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.019784
Epoch: 9 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.036573
Epoch: 9 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.078576
Epoch: 9 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.131681
Epoch: 9 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.068966
Epoch: 10 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.037780
Epoch: 10 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.146228
Epoch: 10 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.046552
Epoch: 10 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.028405
Epoch: 10 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.095194
Epoch: 10 batch #: 6  of 8 sample #: 10000  reconstruction error: 0.064611
Epoch: 10 batch #: 7  of 8 sample #: 10000  reconstruction error: 0.073060
Epoch: 10 batch #: 8  of 8 sample #: 8486  reconstruction error: 0.056897
Epoch: 11 batch #: 1  of 8 sample #: 10000  reconstruction error: 0.050711
Epoch: 11 batch #: 2  of 8 sample #: 10000  reconstruction error: 0.144504
Epoch: 11 batch #: 3  of 8 sample #: 10000  reconstruction error: 0.115517
Epoch: 11 batch #: 4  of 8 sample #: 10000  reconstruction error: 0.030991
Epoch: 11 batch #: 5  of 8 sample #: 10000  reconstruction error: 0.112435

KeyboardInterrupt:

In [18]:
inputUser = tf.convert_to_tensor(X[4826], 'float32')
v0 = inputUser
print(v0)
v0.shape

tf.Tensor(
[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.8 0.  0.7 0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.6 0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.6 0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0. ], shape=(116,), dtype=float32)

TensorShape([116])

In [19]:
hh0 = tf.nn.sigmoid(tf.linalg.matmul([v0], W) + hidden_layer_bias)
vv1 = tf.nn.sigmoid(tf.linalg.matmul(hh0, tf.transpose(W)) + visible_layer_bias)
rec = vv1

tf.maximum(rec, 1)
for i in vv1:
    print(i)

tf.Tensor(
[2.75857619e-05 1.21173160e-02 8.17752909e-04 4.41333104e-05
 8.87783768e-04 6.04161294e-04 4.34125337e-04 2.36740103e-03
 7.98230467e-04 2.19888147e-03 9.53656342e-03 1.66234316e-03
 1.75604873e-04 1.37173093e-03 6.22828351e-03 1.41263381e-01
 7.32804590e-04 1.99275259e-02 1.44176779e-03 1.72629557e-03
 1.43671787e-04 3.36939283e-03 1.24085015e-02 1.07886873e-01
 4.71358100e-04 6.45070195e-01 2.98134744e-01 2.38309026e-01
 1.25126690e-02 1.92027643e-01 7.61906500e-04 1.05344946e-03
 1.65918085e-03 2.34695664e-03 4.67532612e-02 1.85140464e-02
 4.84085962e-04 7.70455599e-02 9.70707799e-04 3.96440097e-04
 3.76604701e-04 6.22659398e-04 1.21714707e-04 1.05270110e-02
 6.60156482e-04 2.71164209e-01 1.10852532e-03 4.34518466e-03
 7.29786092e-03 9.65528190e-02 7.72854983e-05 1.01055938e-03
 6.03990024e-03 7.68122822e-02 7.50363944e-03 1.35663804e-02
 3.65383900e-03 3.55741777e-03 1.23247309e-02 1.27304971e-04
 5.03007462e-03 1.27121503e-03 1.74185753e-01 3.42016901e-05
 6.49581710e-03 1.09677929e-02 1.83523163e-01 3.46262641e-05
 2.58334796e-03 1.01682274e-02 2.65020467e-02 1.02747530e-02
 5.83339133e-04 6.23181053e-02 1.44178409e-06 5.29375277e-04
 3.76966149e-02 2.84425449e-04 9.88054182e-03 1.49703678e-03
 5.13068517e-05 2.93277757e-04 8.45234282e-03 6.78956285e-02
 1.63304945e-03 4.88073420e-04 1.56191806e-03 3.55623476e-03
 8.90094601e-03 1.71420436e-06 2.76001549e-04 4.08995140e-04
 1.78090092e-02 2.36248877e-03 1.37310603e-03 5.60023473e-05
 5.31844124e-02 4.06774320e-02 1.51833097e-04 1.61276773e-01
 6.79705739e-02 1.79435331e-02 2.74239704e-02 8.60987580e-04
 2.04573240e-04 7.05430657e-03 9.62890277e-04 7.80067465e-04
 3.46354209e-03 4.21100158e-05 4.16716612e-05 6.80406753e-04
 6.95205666e-03 1.42949482e-03 1.30028720e-03 1.32721392e-02], shape=(116,), dtype=float32)

In [20]:
scored_df_mock = pd.DataFrame({'Game': normalized_df.columns})
scored_df_mock = scored_df_mock.assign(RecommendationScore = rec[0])
scored_df_mock = scored_df_mock.assign(Actual = X[4826])
scored_df_mock['RecommendationScore'] = scored_df_mock['RecommendationScore'].apply(
    lambda x: round(10 * x, 1)
)
scored_df_mock['Actual'] = scored_df_mock['Actual'].apply(
    lambda x: round(10 * x, 1)
)
scored_df_mock.sort_values(['RecommendationScore'], ascending=False)

,Game,RecommendationScore,Actual
25,Carcassonne,6.5,8.0
26,Chess,3.0,0.0
45,For Sale,2.7,0.0
27,Citadels,2.4,7.0
29,Crokinole,1.9,0.0
...,...,...,...
75,Raid on St. Nazaire,0.0,0.0
16,Black Vienna,0.0,0.0
77,Rise of the Luftwaffe,0.0,0.0
79,Rommel in the Desert,0.0,0.0
0,1826: Railroading in France and Belgium from 1826,0.0,0.0